version: "3"
networks:
  servicenet:
    external: true
services:
  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - "19736:6379"
    volumes:
      - "/mnt/database/redis/redis.conf:/etc/redis/redis.conf"
      - "/mnt/database/redis/data:/data"
    command: redis-server /etc/redis/redis.conf --appendonly yes --requirepass Xinxibu1717...
    logging:
      driver: json-file
      options:
        max-size: "100m"
        max-file: "2"
    networks:
      servicenet: {}